version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
    - '${API_PORT}:${API_PORT}'
    command: npm run start:dev
    networks:
    - chat-network
    links:
    - postgres-db
    volumes:
    - .:/app
  postgres-db:
    image: postgres
    restart: always
    environment:
     POSTGRES_DB: ${POSTGRES_DATABASE}
     POSTGRES_USER: ${POSTGRES_USERNAME}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
    - ./storage/db:/var/lib/postgresqldata
    ports:
    - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
    - chat-network
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
    - '${PGADMIN_PORT}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
    - ./storage/pgadmin-data:/var/lib/pgadmin
    user: '5050'
    networks:
    - chat-network

networks:
  chat-network:
    driver: bridge